// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'EduArt Robotik Tutorials',
      // Klick auf den Titel öffnet die Startseite deiner Doku
      link: {
        type: 'doc',
        id: 'EduArts-Tutorials', // Datei docs/EduArts-Tutorials.mdx
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Simulation',
        },
        {
          type: 'autogenerated',
          dirName: 'rd platform eduard',
        },
      ],
    },
  ],
};
export default sidebars;
