// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'EduArt Robotik Tutorials',
      link: {
        type: 'doc',
        id: 'EduArts-Tutorials',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Simulation',
        },

        /* =====================
           RD Platform Eduard
        ====================== */
        {
          type: 'category',
          label: 'R&D Plattform Eduard',
          link: {
            type: 'generated-index',
            title: 'R&D Plattform Eduard',
          },
          items: [
            {
              type: 'category',
              label: 'Bedienungsanleitung',
              link: {
                type: 'generated-index',
                title: 'Bedienungsanleitung',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'rd platform eduard/Bedienungsanleitung',
                },
              ],
            },
            {
              type: 'category',
              label: 'Komponenten',
              link: {
                type: 'generated-index',
                title: 'Komponenten',
              },
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'rd platform eduard/Komponenten',
                },
              ],
            },
          ],
        },

        /* =====================
           KinematicsKit Kim
        ====================== */
        {
          type: 'category',
          label: 'KinematicsKit Kim',
          link: {
            type: 'generated-index',
            title: 'KinematicsKit Kim',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'kinematicskit kim',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;